# Generated by Django 4.2.1 on 2023-06-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='roll',
        ),
    ]
