# Generated by Django 4.2.1 on 2023-06-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_leaderboard_name_remove_leaderboard_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
